name: FORCE-Visualization
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pangeo-notebook=2020.06.03
  - argopy
  - bokeh
  - bottleneck
  - cartopy <0.18
  - cdsapi
  - cf-units
  - cf_xarray
  - ckanapi
  - colorcet
  - compilers
  - cotede
  - ctd
  - dask
  - datashader
  - descartes
  - erddapy
  - geolinks
  - geopandas
  - geoviews
  - gsw
  - h5netcdf
  - holoviews
  - hvplot
  - intake
  - ioos-tools
  - ioos_qc
  - ipyleaflet
  - jupyter
  - jupyter-rsession-proxy
  - jupyter_contrib_nbextensions
  - jupyterlab
  - jupyter-panel-proxy
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  - numpy
  - oceansdb
  - palettable
  - pandas<1.1
  - panel
  - param
  - podaacpy
  - pyoos
  - rasterio
  - re
  - requests
  - retrying
  - s3fs
  - scipy
  - seaborn
  - seawater
  - shapely
  - siphon
  - xarray
  - xlrd
  - zarr
 # extras
  - conda-lock
  - git
  - graphviz
  - nano
  - unzip
  - vim
  - zip
